alias g='git'
alias ga='git add'
alias gb='git branch -vv'
alias gba='git branch -avv'
alias gbd='git branch -d'
alias gc!='git commit -v --amend'
alias gc='git commit -v'
alias gcb='git checkout -b'
alias gcf='git config --list'
alias gcm='git checkout master'
alias gco='git checkout'
alias gd="git diff --color-words"
alias gf='git fetch'
alias gfc='gll -i --grep'
alias ghh='git help'
alias gl="git --no-pager  log --graph --pretty=format:'%C(yellow)%h%C(cyan)%d%Creset %s %C(white)- %ar%Creset' -20"
alias glg="git log --all --name-status -i --grep"
alias gll="git log --stat --abbrev-commit --date=format:'%a %b %d %Y %T'"
alias glo="git log --graph --pretty='%Cred%h%Creset %C(auto)%d%Creset %s %Cgreen(%ad)' --date=short"
alias gm='git merge'
alias gmo='git merge origin/master'
alias gp='git push'
alias gr='git remote'
alias grb='git rebase'
alias grm='git rm'
alias grs='git restore'
alias grt='cd "$(git rev-parse --show-toplevel || echo .)"'
alias grv='git remote -v'
alias gst='git status'
alias gsw='git switch'
